title: Darlog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Maverick Cloud"
  email: "feruchio599@gmail.com"
  url: "https://github.com/arxero"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

kramdown:
    auto_ids: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Maverick"
year : "2019"